replicaCount: 1

image:
  repository: dataopennesscommunity/demo-golden
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 5000
  targetPort: 5000

ingress:
  enabled: true
  path-prefix: /run-jenkins
  # annotations, hosts, and other configurations go here

resources: {}

url: http://datamgmtdemo01.eastasia.cloudapp.azure.com:8080