replicaCount: 1

image:
  repository: dataopennesscommunity/demo-golden
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: NodePort
  port: 5000
  targetPort: 5000
  nodePort: 30007 # Optional: Specify a nodePort in the range (30000-32767) if you want a specific port, otherwise it will be assigned by Kubernetes

ingress:
  enabled: false
  # annotations, hosts, and other configurations go here

resources: {}

url: http://datamgmtdemo01.eastasia.cloudapp.azure.com:8080